version: '1.0'
services:
  webservice:
    container_name: "PHP-SERVER"
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-srv  
  mysql-srv:  
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: histoire_db
      MYSQL_USER: Steven
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"