<?php

namespace ContainerIz8qgIP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A3Zwdy6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A3Zwdy6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A3Zwdy6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'histoireRepository' => ['privates', 'App\\Repository\\HistoireRepository', 'getHistoireRepositoryService', true],
            'pageRepository' => ['privates', 'App\\Repository\\PageRepository', 'getPageRepositoryService', true],
        ], [
            'histoireRepository' => 'App\\Repository\\HistoireRepository',
            'pageRepository' => 'App\\Repository\\PageRepository',
        ]);
    }
}
