<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_histoire_p1' => [['idHistoire'], ['_controller' => 'App\\Controller\\HistoireController::page1'], [], [['variable', '/', '[^/]++', 'idHistoire', true], ['text', '/histoire']], [], [], []],
    'app_histoire_page' => [['idHistoire', 'numPage'], ['_controller' => 'App\\Controller\\HistoireController::showPage'], [], [['variable', '/', '[^/]++', 'numPage', true], ['text', '/page'], ['variable', '/', '[^/]++', 'idHistoire', true], ['text', '/histoire']], [], [], []],
    'app_histoire_fin' => [['idHistoire'], ['_controller' => 'App\\Controller\\HistoireController::showEndingPage'], [], [['variable', '/', '[^/]++', 'idHistoire', true], ['text', '/histoire/fin']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HistoireController::home'], [], [['text', '/']], [], [], []],
];
